#!/usr/bin/env python3
"""`FailOn` accepts only names it can actually fail on.

IMPROVEMENT_PLAN.md D87. `FailOn=SQLPrepareZ` matched nothing and said
nothing: the connection opened, the mock behaved normally, and the caller's
fault-injection run silently tested the success path instead. That is the same
class D26 fixed one level up, where `FailOn` was inert unless `Mode=Partial`.

A name is failable when it is either

  * an ANSI implementation that consults `should_fail("<name>")` - the literal
    argument at the call site is the name; or
  * one of the W wrappers, which push their own `__func__` as a `WEntryScope`
    (D78) that `should_fail` then matches. All of them reach a consulting
    implementation, `SQLBrowseConnectW` through `SQLDriverConnectW`.

Names outside that union do nothing, and an entry point that simply never
consults `should_fail` is in that set too - naming one is as silent as a typo,
so it is rejected the same way.

The list the driver validates against lives in
`src/driver/fail_on_names.hpp`, because a connection has to check it without
running Python. This recomputes the set from the sources and asserts the
header still matches - the same role as the mockodbc.def drift check (F11).

Usage:
    python3 mock-driver/tools/check_fail_on_names.py            # check
    python3 mock-driver/tools/check_fail_on_names.py --write    # regenerate
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MOCK = os.path.dirname(HERE)
SRC = os.path.join(MOCK, 'src')
HEADER = os.path.join(SRC, 'driver', 'fail_on_names.hpp')
WRAPPERS = os.path.join(SRC, 'odbc', 'unicode_wrappers.cpp')

SHOULD_FAIL_RE = re.compile(r'should_fail\("([A-Za-z0-9_]+)"\)')
W_ENTRY_RE = re.compile(r'^SQLRETURN SQL_API (SQL[A-Za-z0-9_]+W)\(', re.M)
LIST_RE = re.compile(r'kFailOnNames\[\] = \{(.*?)\};', re.S)


def failable_names():
    """Every name `FailOn=` can act on, sorted."""
    names = set()

    for root, _dirs, files in os.walk(SRC):
        for name in files:
            if not name.endswith(('.cpp', '.hpp')):
                continue
            with open(os.path.join(root, name), encoding='utf-8') as fh:
                names.update(SHOULD_FAIL_RE.findall(fh.read()))

    with open(WRAPPERS, encoding='utf-8') as fh:
        names.update(W_ENTRY_RE.findall(fh.read()))

    return sorted(names)


def render(names):
    lines = [
        '#pragma once',
        '',
        '// Generated by mock-driver/tools/check_fail_on_names.py - do not',
        '// edit by hand. Run the tool with --write after adding or removing a',
        '// should_fail() call site or a W wrapper; CI checks it has been run.',
        '//',
        '// D87: the names `FailOn=` can actually act on. Anything else is a',
        '// silent no-op - the connection opens, the mock behaves normally, and',
        '// a fault-injection run quietly exercises the success path instead.',
        '// An entry point that never consults should_fail is in that category',
        '// too, so it is not listed and naming it is rejected like a typo.',
        '',
        '#include <string>',
        '',
        'namespace mock_odbc {',
        '',
        'inline constexpr const char* kFailOnNames[] = {',
    ]
    lines += ['    "%s",' % n for n in names]
    lines += [
        '};',
        '',
        '// Case-insensitive, because `FailOn` is (D26). Takes an already',
        '// lower-cased name so a caller checking a list does not re-lower each',
        '// candidate for every entry.',
        'bool is_failable_entry_point(const std::string& lower_name);',
        '',
        '}  // namespace mock_odbc',
        '',
    ]
    return '\n'.join(lines)


def header_names():
    if not os.path.exists(HEADER):
        return None
    with open(HEADER, encoding='utf-8') as fh:
        m = LIST_RE.search(fh.read())
    if not m:
        return None
    return sorted(re.findall(r'"([A-Za-z0-9_]+)"', m.group(1)))


def main():
    names = failable_names()

    if '--write' in sys.argv:
        with open(HEADER, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(render(names))
        print('wrote %s: %d names' % (os.path.relpath(HEADER, MOCK), len(names)))
        return 0

    current = header_names()
    if current is None:
        print('::error::%s is missing or unparseable; run with --write'
              % os.path.relpath(HEADER))
        return 1

    missing = [n for n in names if n not in current]
    extra = [n for n in current if n not in names]
    if missing or extra:
        print('::error::fail_on_names.hpp has drifted from the sources.')
        if missing:
            print('  failable but not listed: %s' % ', '.join(missing))
        if extra:
            print('  listed but not failable: %s' % ', '.join(extra))
        print('  Run: python3 mock-driver/tools/check_fail_on_names.py --write')
        return 1

    print('FailOn accepts %d names, all of which can fail.' % len(names))
    return 0


if __name__ == '__main__':
    sys.exit(main())
