#pragma once

// Generated by mock-driver/tools/check_fail_on_names.py - do not
// edit by hand. Run the tool with --write after adding or removing a
// should_fail() call site or a W wrapper; CI checks it has been run.
//
// D87: the names `FailOn=` can actually act on. Anything else is a
// silent no-op - the connection opens, the mock behaves normally, and
// a fault-injection run quietly exercises the success path instead.
// An entry point that never consults should_fail is in that category
// too, so it is not listed and naming it is rejected like a typo.

#include <string>

namespace mock_odbc {

inline constexpr const char* kFailOnNames[] = {
    "SQLBindCol",
    "SQLBindParameter",
    "SQLBrowseConnectW",
    "SQLCloseCursor",
    "SQLColAttribute",
    "SQLColAttributeW",
    "SQLColumnPrivileges",
    "SQLColumnPrivilegesW",
    "SQLColumns",
    "SQLColumnsW",
    "SQLConnect",
    "SQLConnectW",
    "SQLDescribeCol",
    "SQLDescribeColW",
    "SQLDescribeParam",
    "SQLDisconnect",
    "SQLDriverConnect",
    "SQLDriverConnectW",
    "SQLEndTran",
    "SQLExecDirect",
    "SQLExecDirectW",
    "SQLExecute",
    "SQLFetch",
    "SQLFetchScroll",
    "SQLForeignKeys",
    "SQLForeignKeysW",
    "SQLGetConnectAttr",
    "SQLGetConnectAttrW",
    "SQLGetCursorName",
    "SQLGetCursorNameW",
    "SQLGetData",
    "SQLGetDescField",
    "SQLGetDescFieldW",
    "SQLGetDescRec",
    "SQLGetDescRecW",
    "SQLGetDiagField",
    "SQLGetDiagFieldW",
    "SQLGetDiagRec",
    "SQLGetDiagRecW",
    "SQLGetFunctions",
    "SQLGetInfo",
    "SQLGetInfoW",
    "SQLGetStmtAttr",
    "SQLGetStmtAttrW",
    "SQLGetTypeInfo",
    "SQLGetTypeInfoW",
    "SQLMoreResults",
    "SQLNativeSql",
    "SQLNativeSqlW",
    "SQLNumParams",
    "SQLNumResultCols",
    "SQLPrepare",
    "SQLPrepareW",
    "SQLPrimaryKeys",
    "SQLPrimaryKeysW",
    "SQLProcedureColumns",
    "SQLProcedureColumnsW",
    "SQLProcedures",
    "SQLProceduresW",
    "SQLRowCount",
    "SQLSetConnectAttr",
    "SQLSetConnectAttrW",
    "SQLSetCursorName",
    "SQLSetCursorNameW",
    "SQLSetDescField",
    "SQLSetDescFieldW",
    "SQLSetDescRec",
    "SQLSetStmtAttr",
    "SQLSetStmtAttrW",
    "SQLSpecialColumns",
    "SQLSpecialColumnsW",
    "SQLStatistics",
    "SQLStatisticsW",
    "SQLTablePrivileges",
    "SQLTablePrivilegesW",
    "SQLTables",
    "SQLTablesW",
};

// Case-insensitive, because `FailOn` is (D26). Takes an already
// lower-cased name so a caller checking a list does not re-lower each
// candidate for every entry.
bool is_failable_entry_point(const std::string& lower_name);

}  // namespace mock_odbc
